### ISSUE TITLE
Finding triples matching a keyword/phrase

### ISSUE THREAD

**Issue by camdirigo** [Callidon/pyHDT#1]
Is there a way of utilizing pyHDT to find triples that contain a given keyword? For instance, when working with the [Semantic Web Dog Food HDT](http://gaia.infor.uva.es/hdt/swdf-2012-11-28.hdt.gz), I first load the data as below:
```
from hdt import HDTDocument
document = HDTDocument("swdf.hdt")
```
I am able to quickly find all the triples containing a given URI if I know that URI beforehand:
`(triples, cardinality) = doc.search_triples("", "", "http://data.semanticweb.org/person/christian-bizer")`
However, there are scenarios where it would be useful to search the HDT for URIs containing the keyword/phrase of interest, such as `christian-bizer`. Is there a way of doing this with pyHDT?

**Comment by Callidon** [comment]
Hi,

If I understand correctly, you want to perform a text-search in RDF terms.
However, PyHDT is only a high-level wrapper over an HDT document, which does not support such functionnality natively (see the original [research paper](https://ac.els-cdn.com/S1570826813000036/1-s2.0-S1570826813000036-main.pdf?_tid=8c3d4d69-c8ff-4393-8ac4-d8ec1fada493&acdnat=1526452564_fb7abf65103755b925e6c26667ddd95a)). The only operations supported are search by subject, predicate and object, with optional limit and offset.

If you want to achieve this, you will need to add custom logic on top of the `search_triples`function to filter triples after fetching them from the HDT document.

**Comment by Callidon** [comment]
Issue closed due to lack of feedback from the issuer.
Feel free to reopen it if there is any update!
