### ISSUE TITLE
Failed building wheel for hdt

### ISSUE THREAD

**Issue by pragal18** [Callidon/pyHDT#2]
Hi.. I am not able to import hdt. 
I am not sure if the prerequisite gcc/clang with c++11 is supported. 
How can I check it in windows? 
How can I download it ?
Logs:
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    triple_iterator.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude -Iinclude -Iinclude/ -Ihdt-cpp-1.3.2/libhdt/include/ -Ihdt-cpp-1.3.2/libhdt/src/dictionary/ -Ihdt-cpp-1.3.2/libcds/include/ -Ihdt-cpp-1.3.2/libcds/src/static/bitsequence -Ihdt-cpp-1.3.2/libcds/src/static/coders -Ihdt-cpp-1.3.2/libcds/src/static/mapper -Ihdt-cpp-1.3.2/libcds/src/static/permutation -Ihdt-cpp-1.3.2/libcds/src/static/sequence -Ihdt-cpp-1.3.2/libcds/src/utils -Ic:\users\new\anaconda3\include -Ic:\users\new\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /EHsc /Tpsrc/tripleid_iterator.cpp /Fobuild\temp.win-amd64-3.7\Release\src/tripleid_iterator.obj -std=c++11

**Comment by Callidon** [comment]
Hi

Given your error, your compiler does not have support for C++11. Sadly, it's a hard requirement for running the core HDT library itself, so you cannot bypass it.

It appears that you use the compiler embedded in Microsoft Visual Studio. I think you should look for a version that supports C++11. Unfortunately, I never worked with these tools so I cannot help you there.

**Comment by Callidon** [comment]
Closing the issue due to the lack of feedback of the user. Feel free to reopen if there is any update.
