### ISSUE TITLE
Search is broken for resources that are not in the graph

### ISSUE THREAD

**Issue by blschatz** [Callidon/pyHDT#3]
In the newest commit, the search function is redefined. 

If I have a graph containing
   A,B,C
and I search for  
  X ? ?
I get all triples in the database as a result
  A,B,C.

Under the 1.1.0 version and hdtSearch I get an empty set as the result.

I suspect that the resource to ID conversion results prior to searching might need to be checked.

**Comment by Callidon** [comment]
Can you please provide a more complete example, with an example RDF dataset and snippets of python code that exhibits the issue?

**Comment by blschatz** [comment]
Please see the PR I submitted.

**Comment by Callidon** [comment]
Ok, but it seems that this is more an issue related to HDT than to this library, which is simply a binding of C++ to Python.

**Comment by blschatz** [comment]
I think if you try the unit test I contributed with your new implementation of the search API and compare it with your earlier version, you'll find that that the semantics of the search operation has changed. Thats an issue with the binding and not the library.

**Comment by Callidon** [comment]
Issue fixed as of release 2.0 (commit 8b18c950ee98ab554d34d9fddacab962d3989b55). Thank you @blschatz for providing the fix (and sorry for the delay for integrating it).
